CREATE TABLE IF NOT EXISTS questions (
    question_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    difficulty TINYINT UNSIGNED NOT NULL,
    torture_score INT UNSIGNED NOT NULL DEFAULT 0,
    source VARCHAR(512) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (question_id),
    CONSTRAINT chk_questions_difficulty
        CHECK (difficulty BETWEEN 1 AND 3)
) ENGINE=InnoDB
    DEFAULT CHARSET=utf8mb4
    COLLATE=utf8mb4_0900_ai_ci;